# Generated by Django 5.0.4 on 2024-06-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InnerFlow', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
